export const FETCH_NEWS = "FETCH_NEWS";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_NEWS_FAILURE = "FETCH_NEWS_FAILURE";

export const FETCH_FAVORITE_NEWS = "FETCH_FAVORITE_NEWS";
export const FETCH_FAVORITE_NEWS_SUCCESS = "FETCH_FAVORITE_NEWS_SUCCESS";
export const FETCH_FAVORITE_NEWS_FAILURE = "FETCH_FAVORITE_NEWS_FAILURE";

export const FETCH_TOP_NEWS = "FETCH_TOP_NEWS";
export const FETCH_TOP_NEWS_SUCCESS = "FETCH_TOP_NEWS_SUCCESS";
export const FETCH_TOP_NEWS_FAILURE = "FETCH_TOP_NEWS_FAILURE";

export const API_KEY = import.meta.env.VITE_NEWS_API_KEY;
export const BASE_URL = "https://newsapi.org/v2";
